Add dashboard code
perryhoffman/design-practice pull request #3
Opened 2018-08-15 23:37 UTC by maiix

2018-08-21 19:17 UTC, perryhoffman requested changes
Looking really good Mayra! I only have a couple of small suggestions/updates for you. Keep up the good work 👍

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/index.html
> +      <a href="#"><span class="btn new"><i class="fas fa-plus"></i> New Request</span></a>
Using a span as a button totally works, usually though the `<button>` tag is preferred!

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/index.html
> +      <span><a href="#"><i class="far fa-comments"></i></a></span>
These icon links are looking good. The `<span>` tags don't seem to be doing a whole lot, I would recommend removing extra tags like this. You will thank yourself when the app gets much larger!

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/index.html
> +      <nav class="left-nav">
👍

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/index.html
> +                </div>
Each of these `badge` components looks really good. Semantic HTML and indentation, nice!

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/css/styles.css
> +.new {
Be **very** careful with short generic class names like this. For a small page it is totally fine, but when the app/site gets larger these types of classes aren't ideal. They aren't descriptive enough and are at a high risk of having a naming clash which will cause toooons of confusion.

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/css/styles.css
> +.header-content {
Class naming like this is much better!

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/css/styles.css
> +.row {
I told kitty the same thing here,  it isn't ideal to overwrite styles of bootstrap/any framework as it makes that change  EVERYWHERE in the app. A better solution could be to make a modifier class like `.row--box-size` and just add it where you need it!

2018-08-21 19:17 UTC, perryhoffman commented on Mayra/css/styles.css
> +.left-nav a:hover > i {
Nice use of the first child selector!

2018-09-06 17:30 UTC, perryhoffman approved these changes
👍

2018-09-06 17:30 UTC, perryhoffman commented on Mayra/css/styles.css
> +button {
Careful, this gives all `button`'s on your site the same style. Was that your intent?

2021-05-28 18:37 UTC, closed without merging

2021-05-28 18:40 UTC, perryhoffman commented
Hiiiii @maiix !! 👋  😆

2021-05-28 18:42 UTC, maiix commented
LOL hi @perryhoffman 👋 👋  I'm playing with my github account 😃